name: Repository Dispatch
on:
  repository_dispatch:
    types: [dispatch-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: pcsvn/pcs-blog-hugo
          ref: ${{ github.event.client_payload.sha }}
