name: Trigger blog to build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: pcsvn/pcs-blog-hugo
          event-type: update
